### ISSUE TITLE
Repo organization

### ISSUE THREAD

**Issue by youssefbm** [Abdeladimboukrim/abdeladimboukrim#1]
please organize your files as i said.

**Comment by Abdeladimboukrim** [comment]
done files organized

**Comment by Abdeladimboukrim** [comment]
@youssefbm

**Comment by youssefbm** [comment]
Nommez correctement les fichiers stp @Abdeladimboukrim

**Comment by youssefbm** [comment]
Nommez correctement les fichiers stp @Abdeladimboukrim

**Comment by Abdeladimboukrim** [comment]
done
